name: Generate Resume PDF

on:
  push:
    branches: [main, master]
    paths:
      - "resume.html"
  workflow_dispatch:

jobs:
  generate-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install puppeteer

      - name: Create PDF directory if it doesn't exist
        run: mkdir -p assets/pdf

      - name: Generate PDF from HTML
        run: |
          cat > generate-pdf.js << 'EOL'
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          const path = require('path');

          async function generatePDF() {
            console.log('Starting PDF generation...');

            const browser = await puppeteer.launch({
              headless: 'new',
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });

            const page = await browser.newPage();

            // Set styles for PDF generation - keeping all content but formatting for PDF
            const optimizedCSS = `
              /* Base styling for print */
              body {
                background-color: white !important;
                color: #333 !important;
                font-family: Arial, Helvetica, sans-serif !important;
                line-height: 1.4 !important;
                font-size: 11pt !important;
              }

              /* Hide elements not needed in PDF */
              .nav-bar, .back-to-top, .download-resume-container, .footer, .github-actions-note {
                display: none !important;
              }

              /* Remove profile picture as requested */
              .profile-pic {
                display: none !important;
              }

              /* Fix name heading - hide PatillaCode but show Gonzalo Fernández */
              h1.profile-title {
                display: none !important;
              }

              /* Make real name the main heading */
              h3.profile-title {
                display: block !important;
                font-size: 22pt !important;
                color: #333 !important;
                margin-top: 10px !important;
                margin-bottom: 10px !important;
                font-weight: bold !important;
              }

              /* Main heading styling */
              h1, h2, h3, h4, h5 {
                color: #333 !important;
                margin-bottom: 0.5rem !important;
              }

              h2 {
                font-size: 14pt !important;
                border-bottom: 1px solid #666 !important;
                color: #333 !important;
                padding-bottom: 3px !important;
                margin-top: 1.3rem !important;
                margin-bottom: 0.7rem !important;
              }

              h3:not(.profile-title) {
                font-size: 12pt !important;
                color: #333 !important;
                margin-bottom: 0.2rem !important;
              }

              /* Header area compacted */
              .header {
                text-align: center !important;
                margin-bottom: 1rem !important;
                padding: 0 !important;
              }

              .profile-subtitle {
                color: #555 !important;
                margin-bottom: 1rem !important;
                font-size: 12pt !important;
              }

              /* Make contact links more compact and clickable */
              .contact-links {
                display: flex !important;
                gap: 1rem !important;
                justify-content: center !important;
                margin-top: 0.5rem !important;
                margin-bottom: 0.8rem !important;
              }

              .contact-link {
                color: #1a73e8 !important;
                text-decoration: underline !important;
              }

              .contact-link svg {
                width: 12px !important;
                height: 12px !important;
                fill: #1a73e8 !important;
              }

              /* Space optimization */
              .container {
                padding: 0.8rem !important;
                max-width: 100% !important;
              }

              .section {
                margin-bottom: 1rem !important;
              }

              .section-content {
                margin-bottom: 0.8rem !important;
              }

              /* Experience items */
              .experience-item, .project-item {
                margin-bottom: 0.8rem !important;
                padding-bottom: 0.8rem !important;
                border-bottom: 1px solid #ddd !important;
              }

              .experience-header, .project-header {
                margin-bottom: 0.2rem !important;
              }

              .experience-date, .project-date {
                color: #555 !important;
                font-size: 10pt !important;
              }

              .experience-position {
                color: #444 !important;
                margin-bottom: 0.2rem !important;
                font-size: 10.5pt !important;
              }

              /* Lists more compact */
              ul, ol {
                margin-bottom: 0.8rem !important;
                padding-left: 1.5rem !important;
              }

              li {
                margin-bottom: 0.2rem !important;
                font-size: 10pt !important;
              }

              /* Paragraphs */
              p {
                margin-bottom: 0.4rem !important;
                font-size: 10pt !important;
              }

              /* Skills section in columns */
              .skills-container {
                display: grid !important;
                grid-template-columns: repeat(3, 1fr) !important;
                gap: 0.8rem !important;
              }

              .skill-category h3 {
                margin-bottom: 0.3rem !important;
                padding-bottom: 0.2rem !important;
                border-bottom: 1px solid #ddd !important;
                font-size: 11pt !important;
              }

              .skill-list li {
                padding-left: 1rem !important;
                font-size: 9.5pt !important;
              }

              .skill-list li::before {
                color: #555 !important;
              }

              /* Make project links hidden but keep projects */
              .project-links {
                display: none !important;
              }

              /* Tech tags more compact */
              .project-tech {
                gap: 0.3rem !important;
                margin-top: 0.5rem !important;
              }

              .tech-tag {
                background-color: #f3f3f3 !important;
                color: #444 !important;
                padding: 0.1rem 0.4rem !important;
                border-radius: 3px !important;
                font-size: 8.5pt !important;
                border: 1px solid #ddd !important;
              }

              /* Make links clickable in PDF */
              a {
                color: #1a73e8 !important;
                text-decoration: none !important;
              }
            `;

            // Get the full path to the HTML file
            const htmlPath = 'file://' + process.cwd() + '/resume.html';
            console.log('Loading HTML from:', htmlPath);

            try {
              await page.goto(htmlPath, {
                waitUntil: 'networkidle0',
                timeout: 60000
              });

              console.log('Page loaded. Applying print styles...');

              // Apply PDF-optimized styles
              await page.addStyleTag({ content: optimizedCSS });

              console.log('Styles applied. Generating PDF...');

              // Generate PDF
              const pdfPath = path.join(process.cwd(), 'assets', 'pdf', 'GonzaloFernandez_Resume.pdf');
              await page.pdf({
                path: pdfPath,
                format: 'A4',
                printBackground: true,
                margin: {
                  top: '15mm',
                  bottom: '15mm',
                  left: '12mm',
                  right: '12mm'
                },
                displayHeaderFooter: false,
                preferCSSPageSize: false
              });

              console.log('PDF generated successfully at:', pdfPath);

              if (fs.existsSync(pdfPath)) {
                console.log('PDF file exists. Size:', fs.statSync(pdfPath).size, 'bytes');

                // Set PDF metadata
                const metadata = {
                  Title: "Gonzalo Fernández - Resume",
                  Author: "Gonzalo Fernández",
                  Subject: "Professional Resume",
                  Keywords: "developer, software engineer, python, django, backend"
                };

                console.log('PDF generation and verification complete.');
              } else {
                console.error('PDF file was not created!');
                process.exit(1);
              }
            } catch (error) {
              console.error('Error during page loading or PDF generation:', error);
              process.exit(1);
            }

            await browser.close();
            console.log('Browser closed. PDF generation complete.');
          }

          generatePDF().catch(err => {
            console.error('Error in PDF generation process:', err);
            process.exit(1);
          });
          EOL

          node generate-pdf.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add assets/pdf/GonzaloFernandez_Resume.pdf
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update resume PDF" && git push)
